POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "username": "vinhky2012",
    "password": "vinhky2012"

}
###
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "username": "admin1234",
    "password": "admin1234"
}

###
GET http://localhost:5000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2M2FjMmM3NGM4ZTI1NDA3MWNmMTE1NjMiLCJpYXQiOjE2NzU0NDEzODl9.LGZwCzA4l-rcOFLHDGANOfs_x3mpLemdcG-urGwOrT0